### PR TITLE
feat: remove active login check at checkout MP-87

### PR DESCRIPTION
**Pull request by emuvente**
We have better security measures than this already in-place, and this just causes friction. A similar change is being made in the api, and this will have to wait for that change to be deployed before this is merged.

### CODE REVIEW

**Review by mcstover — APPROVED** [review]
Oh my, thank you for working through this!

**Review by dyersituations — APPROVED** [review]

**Comment by mcstover** [comment]
It appears we do this in [CC pages too](https://github.com/kiva/ui/blob/main/src/pages/LandingPages/CorporateCampaign/CCLandingPage.vue#L892), any thoughts on if we should also remove here? Seems like it couldn't really hurt...I can create a maintenance task in CIT if need be.

**Comment by emuvente** [comment]
> It appears we do this in [CC pages too](https://github.com/kiva/ui/blob/main/src/pages/LandingPages/CorporateCampaign/CCLandingPage.vue#L892), any thoughts on if we should also remove here? Seems like it couldn't really hurt...

Yeah, I'll do that here too, thanks for pointing that out @mcstover !

**Review by dyersituations — APPROVED** [review]

**Review by mcstover — APPROVED** [review]
Thank you for making the updates in the CC/in-context sections too!

**Pull request merged**
