### PR TITLE
VUE-664 themable class names

### PR DESCRIPTION
**Pull request by ryan-ludwig**
Updates to latest KvComponents which includes the themable class changes. Replaces the now-unavailable static color classes with the themable classes.

### CODE REVIEW

**Comment by ryan-ludwig** [comment]
@eddieferrer @stringtheory Once this is merged, [KvThemeProvider](https://main--608b4cf87f686c00213841b1.chromatic.com/?path=/story/kvthemeprovider--default) component can be used to apply a "dark" and "mint" theme to any children.

**Comment by ryan-ludwig** [comment]
The new class names can browsed on the[ Storybook primitives page](https://main--608b4cf87f686c00213841b1.chromatic.com/). There's also a "dark mode" toggle to see how they look in the dark theme.
image

I'm planning on improving the documentation and clarifying which classes are themable (primary, secondary, danger, etc.) and which are static (black, white, brand) this week.

**Review by emuvente — APPROVED** [review]

**Review by mcstover — APPROVED** [review]
I like that more the commonly used colors have terms to signify their importance.

**Comment by BoulderBrains** [comment]
👀 
Catching up from PTO

**Pull request merged**
