### PR TITLE
fix: [CP-548] Fixing API audience URL

### PR DESCRIPTION
**Pull request by kathrynlovett**
Screen Shot 2023-10-06 at 10 06 56 AM

### CODE REVIEW

**Review by dyersituations — APPROVED** [review]

**Review by mcstover — APPROVED** [review]

**Comment by kathrynlovett** [comment]
@dyersituations @mcstover I think our staging environment is relying on the versioned images for the `ui` project. How can I get these changes in a new versioned release? Do y'all create versions manually or is there another process for that?

**Comment by mcstover** [comment]
@kathrynlovett Do you mean the new staging environment? The prior stage env just received the same tag deployed to dev. We then manually deployed the tag to QA for the testing cycle. The full release is currently created for prod only.

I think what you're talking about is moving to this new `-rc` pre-release process which we don't have an image build for yet in either UI or CPS.

**Comment by kathrynlovett** [comment]
@mcstover no, the `ui` isn't setup for our new `-rc` process yet. It's just looking for the latest version for the project and I wasn't seeing any of the versions with the changes from this PR: https://github.com/kiva/ui/releases
Or are you saying that we only create a versino when deploying to prod?

**Comment by mcstover** [comment]
Well we create a version "tag" on each merge...https://github.com/kiva/ui/tags

**Comment by mcstover** [comment]
Release however, are only created when deploying to prod: https://github.com/kiva/ui/releases

**Comment by kathrynlovett** [comment]
Ah, got it. Thank you! Looks like we do have the version tag we need, and I think we're pointing at it. I guess the only remaining mystery is why I'm still seeing us use the old audience. I'll keep digging. Thank you!

**Pull request merged**
