### PR TITLE
CASH-658 Show category description experiment

### PR DESCRIPTION
**Pull request by foochris**

### CODE REVIEW

**Comment by ksekhri** [comment]
Can you post the experiment info for the admin tool in the comments here as well as the ticket description? Ex:
```
uiexp.checkout_donation_100_text
{"name": "CheckoutDonation100Text","enabled": true,"startTime": "2018-08-29T00:00","endTime": "2020-02-05T17:00","control": {"key": "variant-a","name": "Control (variant-a)"},"variants": {"variant-b": {"name": "Checkout Donation 100 Text Exp"}},"distribution": {"variant-a": 0.5,"variant-b": 0.5}}
string
CASH-570: Checkout donation 100 Text
```

**Comment by foochris** [comment]
uiexp.category_description:

```
{"name":"CategoryDescription","enabled":true,"startTime":"2019-02-01T00:00","endTime":"2020-02-01T00:00","control":{  "key":"variant-a","name":"Control (variant-a)"},"variants":{"variant-a":{"name":"Control (variant a)"},"variant-b":{  "name":"CategoryDescription"}},"distribution":{"variant-a":0.5,"variant-b":0.5}}
```

**Comment by mcstover** [comment]
> uiexp.category_description:
> 
> ```
> {"name":"CategoryDescription","enabled":true,"startTime":"2019-02-01T00:00","endTime":"2020-02-01T00:00","control":{  "key":"variant-a","name":"Control (variant-a)"},"variants":{"variant-a":{"name":"Control (variant a)"},"variant-b":{  "name":"CategoryDescription"}},"distribution":{"variant-a":0.5,"variant-b":0.5}}
> ```

You'll want to drop varian-a from the variants object as it's already declared as the key for control. This set up would give you 3 versions...

**Comment by foochris** [comment]
@mcstover Experiment JSON setting updated.

**Comment by mcstover** [comment]
Thanks @foochris Please add that to all environments. I usually set the one in DEV to 1 for the variant with changes so it's easy to verify there.

**Pull request merged**
