### PR TITLE
typography: settings/subscriptions

### PR DESCRIPTION
**Pull request by ryan-ludwig**
https://www.test.kiva.org/settings/subscriptions
https://www.kiva.org/settings/subscriptions

### CODE REVIEW

**Comment by mcstover** [comment]
This was looking nice in the review earlier today! Ready for code review here?

**Comment by ryan-ludwig** [comment]
@mcstover Yes, thanks for the reminder! Wanted to look at it with fresh eyes today.

**Review by eddieferrer — APPROVED** [review]
Looking good 👍

**Review by emuvente — APPROVED** [review]
Nice!

**Pull request merged**
