### PR TITLE
VUE-484 KvCarousel for homepage loans

### PR DESCRIPTION
**Pull request by ryan-ludwig**
Refactors loan carousel on the homepage to use KvCarousel

Ensures a little more than 1 loan card is always visible on mobile to let the user know they can swipe
Fixes a minor bug where the carousel size would increase when the end of the loans was reached
Prevents page height jumps when loans load in
Gets those buttery swipes

### CODE REVIEW

**Comment by ryan-ludwig** [comment]
Tested in FF and Chrome. Unable to test in IE11 yet, but should be able to once this is in dev.

**Review by mcstover — APPROVED** [review]
These improvements came out of feedback when using this setup on the MVP pages so it's nice to move them back into the homepage as well!

**Review by emuvente — APPROVED** [review]
Awesome!

**Review by eddieferrer — APPROVED** [review]
Woohoo no more window math!

**Pull request merged**
