### PR TITLE
ML2-178 Only show the contents of the lightbox when printing

### PR DESCRIPTION
**Pull request by ryan-ludwig**

### CODE REVIEW

**Comment by ryan-ludwig** [comment]
This applies to printing anytime a lightbox is open, not just managed lending.

**Comment by ryan-ludwig** [comment]
Tried a few ways to go about this. This one seems fairly clean, but I'm def open to other approaches. The main problem is that most printing defaults don't print background colors (including white), so the lightbox is hard to keep looking like a lightbox.

**Comment by emuvente** [comment]
If you want to force a background color to print, you can use this mixin that we had in styleguide:
https://github.com/kiva/styleguide/blob/master/source/css/scss/app/print.scss#L3-L13

**Review by mcstover — APPROVED** [review]

**Comment by ryan-ludwig** [comment]
@emuvente that's amazing, is there anything box-shadow can't do?

**Comment by ryan-ludwig** [comment]
I think just printing the lightbox contents is a good solution. Took a look at how Jira handles printing with lightboxes and it seems similar to this.

**Review by emuvente — APPROVED** [review]
👍

**Pull request merged**
