### PR TITLE
VUE-513 Remove processPageContent

### PR DESCRIPTION
**Pull request by eddieferrer**
* processPageContent was only being used on 2 pages, removed in favor of processPageContentFlat.
* This will make it easier to improve the processPageContentFlat function to process pages with multiple layout references

### CODE REVIEW

**Comment by emuvente** [comment]
I'm actually working on a generic Contentful page component that uses `processPageContent`, because `processPageContentFlat` doesn't let you know the order of the items in `contentGroups`, and it also doesn't let you have more than one content group of a given type. I would really want `processPageContentFlat` to support those things if we're going to get rid of `processPageContent`

**Comment by mcstover** [comment]
@eddieferrer Let's do please keep the `processPageContent` method for now so we can work out some of the ideas of how best to access a dynamic list of ordered content groups in isolation.

**Comment by eddieferrer** [comment]
> I'm actually working on a generic Contentful page component that uses `processPageContent`, because `processPageContentFlat` doesn't let you know the order of the items in `contentGroups`, and it also doesn't let you have more than one content group of a given type. I would really want `processPageContentFlat` to support those things if we're going to get rid of `processPageContent`

@emuvente sounds great, would it be helpful then to merge the refactor of the Thanks/Donate component here? Then at least all the components are using the same current function at the moment. Or should I just trash this PR?

**Comment by mcstover** [comment]
I'm to see the refactor of the other pages if you can keep them that's good progress.

**Comment by emuvente** [comment]
@eddieferrer yeah the refactor of the thanks/donate components would be helpful and it looks good!

**Comment by eddieferrer** [comment]
@mcstover @emuvente Kept the refactor of the 2 components. Left contentful utils as they are. Just FYI, I tested this, and it will not require any changes on contentful.

**Review by emuvente — APPROVED** [review]
👍

**Review by mcstover — APPROVED** [review]

**Pull request merged**
