### PR TITLE
Add client-side kount integration + update some loading sequencing.

### PR DESCRIPTION
**Pull request by mcstover**

### CODE REVIEW

**Comment by mcstover** [comment]
Fixed new setting key and added to dev,qa,stage (true) + prod (false)

**Comment by BoulderBrains** [comment]
👀

**Comment by leoperry** [comment]
@mcstover: Kicking off a dev minor right now... to enable this, do I need to do anything other than set up the settings manager flag and set it to enabled?

**Comment by mcstover** [comment]
@leoperry settings should be in place so you should be good to go.

**Pull request merged**
