### PR TITLE
use apollo preFetch for contentful global promo to prevent full page …

### PR DESCRIPTION
**Pull request by mcstover**
…repaint after async load.

### CODE REVIEW

**Comment by mcstover** [comment]
This is a good start and server renders the content properly. However, the optionality in GlobalPromotionalBannerContentful.vue with regard to which component is rendered prevents the css from being inlined.

One option I'm testing is selectively added the GenericPromoBanner to our vue-style-loader config.
(https://github.com/kiva/ui/blob/master/build/webpack.base.conf.js#L68)
If this works it could be useful for some other items as well...

**Comment by mcstover** [comment]
Ok so this worked and ads a relatively small file. This case is a bit special b/c we almost always have content in this Global Promo space so in my opinion it's an acceptable addition.

image

Server rendered header (js disabled)
image

**Comment by mcstover** [comment]
> This is a good start and server renders the content properly. However, the optionality in GlobalPromotionalBannerContentful.vue with regard to which component is rendered prevents the css from being inlined.
> 
> One option I'm testing is selectively added the GenericPromoBanner to our vue-style-loader config.
> (https://github.com/kiva/ui/blob/master/build/webpack.base.conf.js#L68)
> If this works it could be useful for some other items as well...

Alternatively, we remove the v-if on the components in GlobalPromotionalBannerContentful.vue and push a prop so visibility is handled internally, within GenericPromo...

**Comment by mcstover** [comment]
@emuvente @eddieferrer This seems to produce the correct behavior on the homepage, lend-by-category, and category pages.

**Comment by eddieferrer** [comment]
> > This is a good start and server renders the content properly. However, the optionality in GlobalPromotionalBannerContentful.vue with regard to which component is rendered prevents the css from being inlined.
> > One option I'm testing is selectively added the GenericPromoBanner to our vue-style-loader config.
> > (https://github.com/kiva/ui/blob/master/build/webpack.base.conf.js#L68)
> > If this works it could be useful for some other items as well...
> 
> Alternatively, we remove the v-if on the components in GlobalPromotionalBannerContentful.vue and push a prop so visibility is handled internally, within GenericPromo...
> 
> 🤦 Deleted my last comment b/c I didn't have js turned off and that file was still not inlined... will test some other options...

I believe replacing the v-if with v-show might have worked as well.

**Pull request merged**
