### PR TITLE
expand css linter to enforce specific units

### PR DESCRIPTION
**Pull request by horationunez**

### CODE REVIEW

**Comment by BoulderBrains** [comment]
Nice! I like the thought around this change. Let's all be reminded to stay on the same page. 

My only question is, how does this interact with the rem-calc() declarations we have in the /ui repo? I'm curious if rem-calc() meets the stylelint criteria of a "unit" and will require an ignoreProperty to pass over those instances or if it's not a "unit" and therefore not an issue at all. I'll pull this down in the morning and find out.

**Comment by horationunez** [comment]
@BoulderBrains @emuvente ready for another pass.

**Comment by mcstover** [comment]
Thanks @horationunez  that was a good catch.

For a little background a declaration like this (padding-right: 12 _rem;) was not triggering an error...

**Comment by mcstover** [comment]
@BoulderBrains That was a good question, I had no idea how rem-calc would be handled with new restrictions...

**Comment by horationunez** [comment]
@mcstover it flags `12_rem` but not `12 _rem`. This is what I was referring the other day the 12 alone seems to be perceived as pixels an _rem is an undefined token.

**Pull request merged**
