### PR TITLE
ML2-222 Don't send the raw contentful image

### PR DESCRIPTION
**Pull request by ryan-ludwig**
The images uploaded for Visa's campaign were pretty giant for what they were.
Contentful lets you add query params to dynamically set the height/width/format/quality. Saves a lot of bytes.

Original
image

Using picture
image

### CODE REVIEW

**Comment by eddieferrer** [comment]
Excellent 👍  We should probably be using this in all cases that we get images from contentful? Maybe a nice wrapper component in the future?

**Review by eddieferrer — APPROVED** [review]

**Review by mcstover — APPROVED** [review]
Very cool!

**Comment by ryan-ludwig** [comment]
> We should probably be using this in all cases that we get images from contentful? Maybe a nice wrapper component in the future?
@eddieferrer Yeah, I think it's a good idea to do this for all images from contentful, a wrapper could be handy :)

**Comment by ryan-ludwig** [comment]
Created VUE-483

**Pull request merged**
