### PR TITLE
VUE-432 Move the query into created

### PR DESCRIPTION
**Pull request by ryan-ludwig**

### CODE REVIEW

**Review by mcstover — APPROVED** [review]
This should work fine. I just pushed something similar to the previous branch that i was able to verify the data flow for in my vm.

**Review by emuvente — APPROVED** [review]
I'm surprised this would work, but I guess I just learned something new about apollo!

**Comment by ryan-ludwig** [comment]
🤞

**Comment by mcstover** [comment]
Verified in dev via VPN. Cherry-picked to release.

**Pull request merged**
