### PR TITLE
feat: kv components version updated

### PR DESCRIPTION
**Pull request by roger-in-kiva**
- kv-components version updated

### CODE REVIEW

**Comment by dyersituations** [comment]
Is there a particular feature this is needed for?

**Comment by roger-in-kiva** [comment]
> 



> Is there a particular feature this is needed for?

Are we using shared loan cards here? We have the same issue for clickable loan cards when loading... @dyersituations

**Comment by dyersituations** [comment]
> > 
> 
> > Is there a particular feature this is needed for?
> 
> Are we using shared loan cards here? We have the same issue for clickable loan cards when loading... @dyersituations

We aren't using the new loan card yet in the `ui` repo. Maybe we should close this for now and wait for a feature that needs the updates?

**Comment by roger-in-kiva** [comment]
> > > 
> > 
> > 
> > > Is there a particular feature this is needed for?
> > 
> > 
> > Are we using shared loan cards here? We have the same issue for clickable loan cards when loading... @dyersituations
> 
> We aren't using the new loan card yet in the `ui` repo. Maybe we should close this for now and wait for a feature that needs the updates?

Makes sense, thanks for checking!

**Pull request closed without merging**
