### PR TITLE
feat: redirect challenges to lend/filter

### PR DESCRIPTION
**Pull request by christian14b**
Is any other link missing?

### CODE REVIEW

**Review by roger-in-kiva — APPROVED** [review]

**Comment by dyersituations** [comment]
@christian14b did you search our repositories for `team/challenge`? You can use GitHub to do a org-wide search.

**Comment by dyersituations** [comment]
> @dyersituations the ticket mentioned just portfolio, but is ok to change any other `team/challenge` link I found?

Depends on which links. Let us know what you find.

**Comment by dyersituations** [comment]
> I only found these new links on UI, no links in monolith nor in CPS
> 
> https://github.com/kiva/ui/blob/cff7b04a638b920f04ed4dd576d1634579b95971/src/components/Thanks/ChallengeHeader.vue#L92
> 
> https://github.com/kiva/ui/blob/cff7b04a638b920f04ed4dd576d1634579b95971/src/components/Teams/TeamGoal.vue#L80

Which pages are these links currently found on? It's tough to tell from the component name alone.

**Comment by roger-in-kiva** [comment]
> > I only found these new links on UI, no links in monolith nor in CPS
> > https://github.com/kiva/ui/blob/cff7b04a638b920f04ed4dd576d1634579b95971/src/components/Thanks/ChallengeHeader.vue#L92
> > 
> > https://github.com/kiva/ui/blob/cff7b04a638b920f04ed4dd576d1634579b95971/src/components/Teams/TeamGoal.vue#L80
> 
> Which pages are these links currently found on? It's tough to tell from the component name alone.

As the feature is not completed on the filters page, we should avoid these public cases for now though, thanks and /teams pages.

**Comment by dyersituations** [comment]
> As the feature is not completed on the filters page, we should avoid these public cases for now though, thanks and /teams pages.

If this is indeed the /teams page, you are correct, we should leave them be.

**Review by dyersituations — APPROVED** [review]

**Pull request merged**
