### PR TITLE
feat: add cache control headers to passport redirects

### PR DESCRIPTION
**Pull request by christian14b**
Add `Cache-Control` header `no-store, max-age=0, no-transform` to passportjs redirects.

`/ui-login`
image

`/process-ssr-auth`
image

### CODE REVIEW

**Review by dyersituations — APPROVED** [review]

**Review by emuvente — APPROVED** [review]
That looks like that should do it!

**Review by emuvente — CHANGES_REQUESTED** [review]
Actually, could you also please add those headers to the attemptSilentAuth function and the /error and /ui-logout routes?

**Comment by mcstover** [comment]
Just noting I was able to see these new Cache-Control headers applied to `/process-ssr-auth` in the vm!

**Comment by mcstover** [comment]
I think this one is ready with headers added to all auth routes. @emuvente Are these the updates you requested?

**Review by emuvente — APPROVED** [review]
Thanks, looks great!

**Review by mcstover — APPROVED** [review]

**Pull request merged**
