### PR TITLE
Update Ui Ingress config to use apiVersion: networking.k8s.io/v1 and …

### PR DESCRIPTION
**Pull request by mcstover**
…it's corresponding configuration structure.

### CODE REVIEW

**Comment by mcstover** [comment]
We were able to successfully deploy to the Test env with these configs.

**Review by emuvente — APPROVED** [review]

**Review by JoeTravisKiva — APPROVED** [review]
This looks good. Out of curiosity, did you have to manually add the `meta.helm.sh` annotations in the existing ingress resource?

**Comment by mcstover** [comment]
@JoeTravisKiva I'm not sure which part of our configs you're referring to. Pretty much everything we declare is hand-hewn and not versioned by helm at this point. We can check in and discuss further if you'd like!

**Comment by JoeTravisKiva** [comment]
It's these last two annotations that I had been banging my head against (our ingress doesn't have them, maybe because it's one of the oldest resources that we've got?). 
```
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx-ingress-external
    kubernetes.io/ingress.ssl-redirect: "true"
    meta.helm.sh/release-name: kiva-ui
    meta.helm.sh/release-namespace: kiva-marketplace-qa
```
Helm didn't want to allow for an upgrade because the resource didn't have the `meta.helm.sh/release-name` and  `meta.helm.sh/release-namespace` annotations, but it appears that if we add them by hand, I can get past that.

**Comment by mcstover** [comment]
@JoeTravisKiva Looks like we set those directly in the helm command in Jenkinsfile (https://github.com/kiva/ui/blob/master/Jenkinsfile#L63) The release-name gets picked up as the value after `--install` and we set the `--namespace` too...

**Comment by JoeTravisKiva** [comment]
@mcstover Yeah, we use the same command. I don't know why we didn't automatically get the annotations though.

**Pull request merged**
