### PR TITLE
Grow 171

### PR DESCRIPTION
**Pull request by BoulderBrains**
Start of grow-171

### CODE REVIEW

**Comment by eddieferrer** [comment]
Screen Shot 2020-09-16 at 4 05 12 PM

**Comment by eddieferrer** [comment]
I kept both the right and left arrows, the design seems to imply that only 1 arrow is shown at a time, but I dont think we should make that change...

@ryan-ludwig thanks for your work on the carousel, and the cause carousel example, made this very straight forward. Also makes the component a lot cleaner without having to use our custom touch/scroll methods. 

Theres some weird scrolling behavior where its not really snapping to the cause circles. I tried both embla `containScroll` options but it didnt make a difference. I think it may have to do with there not being enough causes to slide to? 

The design has all 9 cause categories displayed. Is this a change we're making? I just left it at the original 5 categories we had as it was not clear to me if we are adding categories. I know `refugees` was removed because it didnt have enough loans at the time.

**Comment by emuvente** [comment]
> The design has all 9 cause categories displayed. Is this a change we're making? I just left it at the original 5 categories we had as it was not clear to me if we are adding categories. I know refugees was removed because it didnt have enough loans at the time.

Good catch! I'll as product + design about that

**Review by emuvente — APPROVED** [review]
👍

**Comment by BoulderBrains** [comment]
👀 👍 
Thanks for taking this @eddieferrer

**Pull request merged**
