### PR TITLE
feat: Add name property to every vue component

### PR DESCRIPTION
**Pull request by edwinf-barreram**
# Description

- Added name property to every vue component.

# Ticket 

[MARS-130](https://kiva.atlassian.net/browse/MARS-130)

### CODE REVIEW

**Comment by dyersituations** [comment]
Just out of curiosity, does this help with caching other than in relation to the Vue `keep-alive` component?

**Comment by edwinf-barreram** [comment]
@dyersituations It is the first step of the process, next ticket is to add the catching strategy. Please see [MARS-131](https://kiva.atlassian.net/browse/MARS-131)

**Comment by dyersituations** [comment]
> @dyersituations It is the first step of the process, next ticket is to add the catching strategy. Please see [MARS-131](https://kiva.atlassian.net/browse/MARS-131)

@edwinf-barreram Ah gotcha, thanks for the info, SSR caching!

**Review by mcstover — APPROVED** [review]
Swashie says thanks you!

**Review by emuvente — APPROVED** [review]
👍  Looks great! Thanks for going through all those files!

**Pull request merged**
