### PR TITLE
fix: turn off apollo batching for ui in all evns including prod

### PR DESCRIPTION
**Pull request by mcstover**
Preparation for changes to api infra

### CODE REVIEW

**Review by dyersituations — APPROVED** [review]

**Comment by kathrynlovett** [comment]
Does this need to be updated for the EKS side as well? It uses the dynamic config: https://github.com/kiva/ui/blob/main/config/dynamic.js#L3

**Comment by mcstover** [comment]
> Does this need to be updated for the EKS side as well? It uses the dynamic config: https://github.com/kiva/ui/blob/main/config/dynamic.js#L3

i don't think dynamic config needs to change. We are passing in `false` via flux for the envs that use that and batching is already off there. I'll double check the prod config for ui in flux though!

**Review by kathrynlovett — APPROVED** [review]
LGTM! 🚀

**Review by JoeTravisKiva — APPROVED** [review]

**Comment by mcstover** [comment]
@emuvente I think we need to go ahead with this update, please review.

**Review by emuvente — APPROVED** [review]
Let's do it!

**Pull request merged**
