### PR TITLE
update research page

### PR DESCRIPTION
**Pull request by go-bears**
add new articles,
fix some broken links & typos

### CODE REVIEW

**Review by mcstover — APPROVED** [review]

**Comment by mcstover** [comment]
Please check the failing build and fix up the errors before merging

**Comment by go-bears** [comment]
thanks for approving! I'm not authorized to merge the PR b/c master is protected branch? Did I miss a check or another review process?

**Comment by go-bears** [comment]
thanks @mcstover !

**Review by BoulderBrains — COMMENTED** [review]
👀 👍

**Pull request merged**
