### PR TITLE
Created loan count display

### PR DESCRIPTION
**Pull request by dymonda21**
I have imported the data for the loan count and displayed it onto the website.

https://kiva.atlassian.net/browse/PSD-279?atlOrigin=eyJpIjoiMzVhNmFiMWQzNzRlNGQ1NGJjNzRjZjgwMzYzZjBkNGQiLCJwIjoiaiJ9

The way that you could test this is by loading up the site and noticing that the loan count has appeared. From there you can minimize your screen so that you can see the responsiveness of the loan count. It will then move from being under the search box to next to the filter tap at the top left.

### CODE REVIEW

**Comment by go-bears** [comment]
@emuvente @ryan-ludwig I'm seeing the same failure in my WIP builds for the Lighthouse CI. Do you think there may be a glitch in the CI tooling?

**Comment by ryan-ludwig** [comment]
> @emuvente @ryan-ludwig I'm seeing the same failure in my WIP builds for the Lighthouse CI. Do you think there may be a glitch in the CI tooling?

Yeah, this seems to be happening on all PRs at the moment. Nothing related to this PR.

**Review by ryan-ludwig — APPROVED** [review]
Looks good! The [linter is squawking](https://github.com/kiva/ui/pull/3141/files) about wanting a space in between the brackets in your template, `{{ foo }}` instead of `{{foo}}`. Aside from that it works well!

**Review by meganmcmillan — COMMENTED** [review]
Wow, you weren't kidding when you said it was simpler than we thought it would be! Yay to seeing live data on this page 🙌 
Nice team work @go-bears @dymonda21 @ryan-ludwig 

Other than the spacing that the linters called out, this looks good to me 👍

**Review by go-bears — COMMENTED** [review]
great job, @dymonda21  !
looks good to me, once the linter issues are fixed.

**Review by go-bears — APPROVED** [review]

**Pull request merged**
