### PR TITLE
VUE-483 kv-contentful-img

### PR DESCRIPTION
**Pull request by ryan-ludwig**
A component to give devs good image sizing and compression without much thought when using images from Contentful.

Implements the component on the homepage and managed lending pages.

### CODE REVIEW

**Comment by ryan-ludwig** [comment]
Some good filesize and request gains so far! 
image

**Review by emuvente — APPROVED** [review]
Looks great! Great improvements to page size as well! 👍

**Review by BoulderBrains — APPROVED** [review]
Nice, once this is merged I'll use this new component for the section i'm currently building out. 👍

**Review by mcstover — APPROVED** [review]

**Review by eddieferrer — APPROVED** [review]
Nice!

**Pull request merged**
