### PR TITLE
grow-388 adding beforeRouteUpdate() to allow MFA methods list to upda…

### PR DESCRIPTION
**Pull request by BoulderBrains**
…te without page refresh

Grow-388: https://kiva.atlassian.net/browse/GROW-388

Adding in a navigation guard which detects the change and updates the page with the changes without the user having to refresh. 

Vue navigation guards:
https://router.vuejs.org/guide/advanced/navigation-guards.html#in-component-guards

Coincides with these /kiva/main changes: 
https://github.com/kiva/kiva/pull/9559

### CODE REVIEW

**Review by mcstover — APPROVED** [review]
Code wise this is correct. Have you been able to verify that the action does in fact trigger this hook? I think the path segments will need to change to trigger this.

**Comment by BoulderBrains** [comment]
@mcstover I tested this locally and it was working, adding MFA methods correctly updated the user's list of MFA methods without refreshing the page.

**Review by mcstover — APPROVED** [review]

**Comment by BoulderBrains** [comment]
Verified and working ✔️

**Review by emuvente — APPROVED** [review]
👍

**Pull request merged**
