### PR TITLE
CASH-1095: Add shared loan object for our reference

### PR DESCRIPTION
**Pull request by ksekhri**

### CODE REVIEW

**Comment by ksekhri** [comment]
@mcstover for reference, just making sure we're all using same loan object

**Comment by emuvente** [comment]
I'd rather that we let the info panels each do their own querying/readFragment calls based on the passed loan id

**Comment by ksekhri** [comment]
@emuvente let's discuss offline @BoulderBrains

**Comment by mcstover** [comment]
@emuvente I can see that being useful for the Partner and Loan Detail panels but overkill for the Overview/Image + Story panel...

**Comment by ksekhri** [comment]
Closing this in favor of #1012

**Pull request closed without merging**
