### PR TITLE
Setup GH actions for PR validations

### PR DESCRIPTION
**Pull request by mcstover**
Y'all ready for this!?!?

### CODE REVIEW

**Comment by mcstover** [comment]
I can pull out the travis deps in this pr or a following pr...

**Comment by mcstover** [comment]
Github action based tests are done: 9mins.

**Review by emuvente — APPROVED** [review]
This is awesome!

**Review by BoulderBrains — APPROVED** [review]
🥳

**Review by ryan-ludwig — APPROVED** [review]
Nice!

**Comment by mcstover** [comment]
Ok waited 2 hours and travis is still queued...

**Pull request merged**
